### ISSUE TITLE
webpack_env 관련 오류 발생

### ISSUE THREAD

**Issue by minji9360** [minji9360/greenday#1]
### 에러 문구
```
'WEBPACK_ENV'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는 배치 파일이 아닙니다.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! greenday@1.0.0 dev:assets: `WEBPACK_ENV=development webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the greenday@1.0.0 dev:assets script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MINJI\AppData\Roaming\npm-cache\_logs\2020-12-02T22_07_30_587Z-debug.log
```

### 상황
webpack을 사용하기 위해 npm 설치
개발용과 배포용을 나누기 위해 package.json script 속성에
"dev:assets": "WEBPACK_ENV=development webpack",
"build:assets": "WEBPACK_ENV=production webpack"
작성 후 저장
npm run dev:assets와 npm run build:assets 두 명령어 모두 같은 에러 메시지 출력

**Comment by minji9360** [comment]
cross-env 설치 후 WEBPACK_ENV 앞에 cross-env 추가하면 해결된다는 방법 발견

- npm cache clean --force
- npm i
- npm install -D cross-env

실행 후 scripts 명령어도 수정했더니 새로운 오류 발생

```
[webpack-cli] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\MINJI\Desktop\greenday\webpack.config.js
require() of ES modules is not supported.
require() of C:\Users\MINJI\Desktop\greenday\webpack.config.js from C:\Users\MINJI\Desktop\greenday\node_modules\webpack-cli\lib\groups\resolveConfig.js is an ES module file as 
it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename webpack.config.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\MINJI\Desktop\greenday\package.json.        

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:13)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (C:\Users\MINJI\Desktop\greenday\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at requireConfig (C:\Users\MINJI\Desktop\greenday\node_modules\webpack-cli\lib\groups\resolveConfig.js:73:18)
    at Array.map (<anonymous>)
    at resolveConfigFiles (C:\Users\MINJI\Desktop\greenday\node_modules\webpack-cli\lib\groups\resolveConfig.js:124:40)
    at module.exports (C:\Users\MINJI\Desktop\greenday\node_modules\webpack-cli\lib\groups\resolveConfig.js:247:11)
    at WebpackCLI._baseResolver (C:\Users\MINJI\Desktop\greenday\node_modules\webpack-cli\lib\webpack-cli.js:53:38) {
  code: 'ERR_REQUIRE_ESM'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! greenday@1.0.0 dev:assets: `cross-env WEBPACK_ENV=development webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the greenday@1.0.0 dev:assets script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MINJI\AppData\Roaming\npm-cache\_logs\2020-12-02T22_10_24_562Z-debug.log
```
