### ISSUE TITLE
ReferenceError: __dirname is not defined

### ISSUE THREAD

**Issue by minji9360** [minji9360/greenday#2]
### 에러문구
```
file:///C:/Users/MINJI/Desktop/greenday/src/app.js:17
app.set("views", path.join(__dirname, "views"));
                           ^

ReferenceError: __dirname is not defined
    at file:///C:/Users/MINJI/Desktop/greenday/src/app.js:17:28
    at ModuleJob.run (internal/modules/esm/module_job.js:139:37)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```

### 상황
view 폴더를 현재 디렉토리 안에서 찾지 않고 계속 바깥에서 찾는 오류 발생
app.js에 아래 코드를 추가하면 될까 싶어 추가했더니 __dirname을 찾지 못한다는 오류가 발생했다.
```
app.set("views", path.join(__dirname, "views"));
```

**Comment by minji9360** [comment]
해당 오류는 해결했으나 view 폴더를 찾지 못하는 오류는 해결되지 않음
